export const metadata = {
  title: "Terms of Service | Finanyst",
  description: "Finanyst terms of service.",
}

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-24">
      <h1 className="font-display text-5xl mb-4 text-foreground">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-12">Last updated: {new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}</p>

      <div className="prose prose-neutral max-w-none space-y-6 text-foreground">
        <p className="text-lg leading-relaxed">
          These are the summary terms for using Finanyst. Full legal terms are being finalised.
        </p>

        <h2 className="font-display text-2xl mt-8">The service</h2>
        <p>Finanyst provides AI-powered financial modelling software. We generate institutional-quality financial models based on the information you provide, with AI-suggested defaults powered by Claude AI.</p>

        <h2 className="font-display text-2xl mt-8">Not financial advice</h2>
        <p>The models and suggestions generated by Finanyst are for informational and analytical purposes only. They do not constitute financial, investment, tax, legal, or accounting advice. You should consult qualified professionals before making financial decisions. Finanyst is not liable for decisions made based on model outputs.</p>

        <h2 className="font-display text-2xl mt-8">Subscription and billing</h2>
        <p>Paid subscriptions renew monthly unless cancelled. You can cancel anytime via the built-in Stripe billing portal. Refunds are handled case-by-case; contact us at <a href="mailto:hello@finanyst.com" className="text-primary hover:underline">hello@finanyst.com</a> if you need to discuss.</p>

        <h2 className="font-display text-2xl mt-8">Acceptable use</h2>
        <p>You agree not to use Finanyst for illegal purposes, to attempt to breach the service&apos;s security, or to resell or redistribute the platform without authorisation. Vendor Pro subscribers may deliver models to their clients under their own branding.</p>

        <h2 className="font-display text-2xl mt-8">Contact</h2>
        <p>For any questions about these terms, please email <a href="mailto:hello@finanyst.com" className="text-primary hover:underline">hello@finanyst.com</a>. Full terms of service documentation will be published shortly.</p>
      </div>
    </main>
  )
}
