import type { InvestorMemo } from "./types"

/**
 * Converts an InvestorMemo to a rich markdown string.
 * Output is formatted for pasting into Notion, Google Docs, email, or Slack.
 * All sections use proper markdown (H1/H2 headings, tables, bullet lists).
 */
export function memoToMarkdown(memo: InvestorMemo, businessName?: string): string {
  const parts: string[] = []

  // -- Header --
  parts.push(`# Investor Memo${businessName ? `: ${businessName}` : ""}`)
  parts.push("")
  parts.push(
    `_Generated: ${new Date(memo.generatedAt).toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })}_`
  )
  parts.push("")
  parts.push("---")
  parts.push("")

  // -- Executive Summary --
  parts.push("## Executive Summary")
  parts.push("")
  parts.push(memo.executiveSummary.businessOneLiner)
  parts.push("")
  parts.push(memo.executiveSummary.financialPunchline)
  parts.push("")
  if (memo.executiveSummary.ask) {
    parts.push(`**${memo.executiveSummary.ask}**`)
    parts.push("")
  }

  // -- Business Snapshot --
  parts.push("## Business Snapshot")
  parts.push("")
  parts.push(`- **Sector:** ${memo.businessSnapshot.sector}`)
  parts.push(`- **Sub-sector:** ${memo.businessSnapshot.subSector}`)
  parts.push(`- **Stage:** ${memo.businessSnapshot.stage}`)
  parts.push(`- **Location:** ${memo.businessSnapshot.location}`)
  parts.push(`- **Model type:** ${memo.businessSnapshot.modelArchetype}`)
  parts.push("")
  parts.push(memo.businessSnapshot.currentState)
  parts.push("")

  // -- Financial Highlights --
  parts.push("## Financial Highlights")
  parts.push("")
  parts.push("| Metric | Year 1 | Year 2 | Year 3 |")
  parts.push("|--------|--------|--------|--------|")
  memo.financialHighlights.metricsTable.forEach((row) => {
    parts.push(`| ${row.metric} | ${row.y1} | ${row.y2} | ${row.y3} |`)
  })
  parts.push("")
  parts.push(memo.financialHighlights.narrative)
  parts.push("")

  // -- Benchmark Comparison --
  if (memo.benchmarkComparison && memo.benchmarkComparison.length > 0) {
    parts.push("## Benchmark Comparison")
    parts.push("")
    memo.benchmarkComparison.forEach((row) => {
      parts.push(`**${row.metric}** — ${row.delta}`)
      parts.push(`- This model: ${row.thisModel}`)
      parts.push(`- Benchmark: ${row.benchmark}`)
      parts.push("")
    })
  }

  // -- Key Assumptions --
  parts.push("## Key Assumptions")
  parts.push("")
  memo.assumptions.keyAssumptions.forEach((a) => {
    parts.push(`### ${a.assumption} — **${a.value}**`)
    parts.push("")
    parts.push(a.rationale)
    parts.push("")
    parts.push(`_${a.benchmarkContext}_`)
    parts.push("")
  })

  // -- Sensitivity --
  parts.push("## Sensitivity Analysis")
  parts.push("")
  parts.push("### Top sensitivities")
  parts.push("")
  memo.sensitivity.topSensitivities.forEach((s) => {
    parts.push(`**${s.variable}:** ${s.impact}`)
    parts.push("")
  })
  parts.push("### Scenario ranges")
  parts.push("")
  parts.push(`- **Bear case:** ${memo.sensitivity.revenueRange.bear}`)
  parts.push(`- **Base case:** ${memo.sensitivity.revenueRange.base}`)
  parts.push(`- **Bull case:** ${memo.sensitivity.revenueRange.bull}`)
  parts.push("")

  // -- Risks --
  parts.push("## Risks & Mitigations")
  parts.push("")
  memo.risks.forEach((r, i) => {
    parts.push(`### Risk ${i + 1}`)
    parts.push("")
    parts.push(r.risk)
    parts.push("")
    parts.push(`**Mitigation:** ${r.mitigation}`)
    parts.push("")
  })

  // -- Capital Ask (conditional) --
  if (memo.capitalAsk) {
    parts.push("## Capital Ask")
    parts.push("")
    parts.push(`- **Round size:** ${memo.capitalAsk.roundSize}`)
    parts.push(`- **Runway:** ${memo.capitalAsk.runway}`)
    parts.push(`- **Next milestone:** ${memo.capitalAsk.nextMilestone}`)
    parts.push("")
    parts.push("**Use of funds:**")
    parts.push("")
    memo.capitalAsk.useOfFunds.forEach((use) => {
      parts.push(`- ${use}`)
    })
    parts.push("")
  }

  // -- Footer --
  parts.push("---")
  parts.push("")
  parts.push(
    "_Generated by Finanyst — driver-based revenue model, balance sheet integrity checks passed, AI-suggested assumptions with sources._"
  )
  parts.push("")
  parts.push(
    "_This memo is analytical, not advisory. It should not be construed as investment advice or a recommendation to buy or sell any security._"
  )

  return parts.join("\n")
}
